export const GET_PROJECTS_FETCHING = 'GET_PROJECTS_FETCHING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';

export const SET_CURRENT_PROJECT_FETCHING = 'SET_CURRENT_PROJECT_FETCHING';
export const SET_CURRENT_PROJECT_SUCCESS = 'SET_CURRENT_PROJECT_SUCCESS';
export const SET_CURRENT_PROJECT_FAILURE = 'SET_CURRENT_PROJECT_FAILURE';

export const CREATE_PROJECT_FETCHING = 'CRETE_PROJECT_FETCHING';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECTS_FAILURE = 'CREATE_PROJECTS_FAILURE';

export const AUTH_FETCHING = 'AUTH_FETCHING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const GET_TEAM_FETCHING = 'GET_TEAM_FETCHING';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_CANDIDATES_SUCCESS = 'GET_TEAM_CANDIDATES_SUCCESS';
export const GET_TEAM_FAILURE = 'GET_TEAM_FAILURE';

export const SUBMIT_ISSUE_FETCHING = 'SUBMIT_ISSUE_FETCHING';
export const SUBMIT_ISSUE_SUCCESS = 'SUBMIT_ISSUE_SUCCESS';
export const SUBMIT_ISSUE_FAILURE = 'SUBMIT_ISSUE_FAILURE';
